/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as GaragensRouteImport } from './routes/garagens'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CarrosRouteImport } from './routes/carros'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrosIdRouteImport } from './routes/carros.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminSimulacoesRouteImport } from './routes/admin.simulacoes'
import { Route as AdminPatrocinadoresRouteImport } from './routes/admin.patrocinadores'
import { Route as AdminAlertasRouteImport } from './routes/admin.alertas'

const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const GaragensRoute = GaragensRouteImport.update({
  id: '/garagens',
  path: '/garagens',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosRoute = CarrosRouteImport.update({
  id: '/carros',
  path: '/carros',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosIdRoute = CarrosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarrosRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSimulacoesRoute = AdminSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatrocinadoresRoute = AdminPatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/carros': typeof CarrosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/garagens': typeof GaragensRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/planos': typeof PlanosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/simulador': typeof SimuladorRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresRoute
  '/admin/simulacoes': typeof AdminSimulacoesRoute
  '/api/chat': typeof ApiChatRoute
  '/carros/$id': typeof CarrosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/carros': typeof CarrosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/garagens': typeof GaragensRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/planos': typeof PlanosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/simulador': typeof SimuladorRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresRoute
  '/admin/simulacoes': typeof AdminSimulacoesRoute
  '/api/chat': typeof ApiChatRoute
  '/carros/$id': typeof CarrosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/carros': typeof CarrosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/garagens': typeof GaragensRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/planos': typeof PlanosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/simulador': typeof SimuladorRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresRoute
  '/admin/simulacoes': typeof AdminSimulacoesRoute
  '/api/chat': typeof ApiChatRoute
  '/carros/$id': typeof CarrosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertas'
    | '/auth'
    | '/avaliacao'
    | '/carros'
    | '/dashboard'
    | '/garagens'
    | '/patrocinadores'
    | '/planos'
    | '/quem-somos'
    | '/simulador'
    | '/admin/alertas'
    | '/admin/patrocinadores'
    | '/admin/simulacoes'
    | '/api/chat'
    | '/carros/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alertas'
    | '/auth'
    | '/avaliacao'
    | '/carros'
    | '/dashboard'
    | '/garagens'
    | '/patrocinadores'
    | '/planos'
    | '/quem-somos'
    | '/simulador'
    | '/admin/alertas'
    | '/admin/patrocinadores'
    | '/admin/simulacoes'
    | '/api/chat'
    | '/carros/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertas'
    | '/auth'
    | '/avaliacao'
    | '/carros'
    | '/dashboard'
    | '/garagens'
    | '/patrocinadores'
    | '/planos'
    | '/quem-somos'
    | '/simulador'
    | '/admin/alertas'
    | '/admin/patrocinadores'
    | '/admin/simulacoes'
    | '/api/chat'
    | '/carros/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertasRoute: typeof AlertasRoute
  AuthRoute: typeof AuthRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  CarrosRoute: typeof CarrosRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  GaragensRoute: typeof GaragensRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PlanosRoute: typeof PlanosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SimuladorRoute: typeof SimuladorRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garagens': {
      id: '/garagens'
      path: '/garagens'
      fullPath: '/garagens'
      preLoaderRoute: typeof GaragensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carros': {
      id: '/carros'
      path: '/carros'
      fullPath: '/carros'
      preLoaderRoute: typeof CarrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carros/$id': {
      id: '/carros/$id'
      path: '/$id'
      fullPath: '/carros/$id'
      preLoaderRoute: typeof CarrosIdRouteImport
      parentRoute: typeof CarrosRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/simulacoes': {
      id: '/admin/simulacoes'
      path: '/simulacoes'
      fullPath: '/admin/simulacoes'
      preLoaderRoute: typeof AdminSimulacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patrocinadores': {
      id: '/admin/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/admin/patrocinadores'
      preLoaderRoute: typeof AdminPatrocinadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminPatrocinadoresRoute: typeof AdminPatrocinadoresRoute
  AdminSimulacoesRoute: typeof AdminSimulacoesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminPatrocinadoresRoute: AdminPatrocinadoresRoute,
  AdminSimulacoesRoute: AdminSimulacoesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CarrosRouteChildren {
  CarrosIdRoute: typeof CarrosIdRoute
}

const CarrosRouteChildren: CarrosRouteChildren = {
  CarrosIdRoute: CarrosIdRoute,
}

const CarrosRouteWithChildren =
  CarrosRoute._addFileChildren(CarrosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertasRoute: AlertasRoute,
  AuthRoute: AuthRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  CarrosRoute: CarrosRouteWithChildren,
  DashboardRoute: DashboardRoute,
  GaragensRoute: GaragensRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PlanosRoute: PlanosRoute,
  QuemSomosRoute: QuemSomosRoute,
  SimuladorRoute: SimuladorRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
